name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get actual task definition
        id: task-def
        run: |
          aws ecs describe-task-definition \
            --task-definition MyflaskApp \
            --query 'taskDefinition' \
            --output json > task-def.json

      - name: Edit actual definition
        run: |
          jq '.containerDefinitions[0].imagePullBehavior="always"' task-def.json > new-task-def.json

      - name: Register new definition
        id: register-task-def
        run: |
          aws ecs register-task-definition \
            --cli-input-json file://new-task-def.json > register-task-def.json
          echo "::set-output name=task-def-arn::$(cat register-task-def.json | jq -r '.taskDefinition.taskDefinitionArn')"

      - name: Update service
        run: |
          aws ecs update-service \
            --cluster MyECSCluster \
            --service MyECSService \
            --task-definition ${{ steps.register-task-def.outputs.task-def-arn }}
