name: simple
on: 
  workflow_dispatch:
env:
  docker_pass: ${{ secrets.DOCKER_PASS }}
  docker_user: ${{ secrets.DOCKER_USERNAME }}
  app_name: ${{ vars.IMAGE_NAME }}
jobs:
   avoid_redundancy:
     runs-on: ubuntu-latest ##ubuntu-20.04
     steps:
       - name: Cancel Workflow Action
         uses: styfle/cancel-workflow-action@0.12.1
         with:
           access_token: ${{ github.token }}

   e2e-test:
     runs-on: ubuntu-latest
     container:
       image: python:3.13
     services:
       selenium:
         image: selenium/standalone-chrome:latest
         ports:
           - 4444:4444
         options: >-
           --health-cmd="curl -s http://localhost:4444/wd/hub/status | grep 'ready' || exit 1"
           --health-interval=5s
           --health-timeout=5s
           --health-retries=3
         env:
           SE_OPENTELEMETRY_TRACING: 0

       app:
         image: lroquec/cicd-tests:latest
         ports:
           - 5000:5000
         options: >-
           --health-cmd="curl -f http://127.0.0.1:5000 || exit 1"
           --health-interval=10s
           --health-timeout=5s
           --health-retries=5
     steps:
       - uses: actions/checkout@v4       
       - name: install requirements with pip
         run: |
           pip install selenium
           pip install pytest
       - name: Run Selenium Tests
         env:
           SELENIUM_REMOTE_URL: http://selenium:4444/wd/hub
         run: |
           python3 -m pytest tests/ -s --junitxml=report.xml
       - name: Upload Selenium results
         uses: actions/upload-artifact@v4
         with:
           name: selenium-test-results
           path: test-reports/
           retention-days: 1